cuts:
  th2cut: 0.008
  
data:
  anasum: /home/sajan/research/EDAnalysis/v2DL3_example/

fileio:
  outdir: /home/sajan/research/EDAnalysis/v2DL3_example/

selection:
  emax: 10
  emin: 0.1
  exc_on_region_radius: 0.3
  exc_radius: 0.3
  nbin: 6
  target: Crab
