[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gammapy_plugin"
description = "The gammapy plugin for 3ML"
readme = "README.md"
authors = [
	{name="Tobias Preis",email="tobias.preis@uibk.ac.at"},
	{name="J. Michael Burgess",email="jburgess@mpe.mpg.de"}
]
maintainers = [ 
	{name="Tobias Preis",email="tobias.preis@uibk.ac.at"}
]
license = "GPL-3.0"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Physics",
]
dynamic = ["version"]
dependencies = [
    "numpy",
    "matplotlib",
    "astromodels",
    "threeml",
    "gammapy>=2.0",
]

[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "filelock",
]
flake = ["flake8"]

[project.urls]
Homepage = "https://github.com/threeML/gammapy-plugin"
Issues = "https://github.com/threeML/gammapy-plugin/issues"


[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"gammapy_plugin.data.datasets" =  ["*.py","*.fits"]

[tool.setuptools_scm]
# Configure custom options here (version schemes, file writing, etc.)
version_file = "gammapy_plugin/_version.py"

# Example: Git-specific configuration
[tool.setuptools_scm.scm.git]
pre_parse = "fail_on_missing_submodules"  # Fail if submodules are not initialized
describe_command = "git describe --dirty --tags --long --exclude *js*"  # Custom Git describe command

[tool.pytest]
addopts = ["--color=yes","-ra"]
testpaths = ["gammapy_plugin/test"]

[tool.isort]
profile = "black"
