
[metadata]
name = gammapy_plugin
description = The gammapy plugin for 3ML
long_description = file:README.md
long_description_content_type = text/markdown
url = https://github.com/grburgess/gammapy_plugin
author_email = jburgess@mpe.mpg.de
author = J. Michael Burgess
requires_python = >=3.3.0
license = GPL-2+

classifiers =
    Development Status :: 2 - Pre-Alpha
    Environment :: Console
    Intended Audience :: Science/Research
    License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
    Operating System :: POSIX
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Topic :: Scientific/Engineering :: Physics

project_urls =
    Bug Tracker = https://github.com/threeML/gammapy_plugin/issues
    Source Code = https://github.com/threeML/gammapy_plugin


[options]
packages = find:
install_requires =
    numpy
    matplotlib
    rich
    omegaconf
    astromodels
    threeml
    gammapy


tests_require =
    pytest
    pytest-codecov


[tool:pytest]
# Options for py.test:
# Specify command line options as you would do when invoking py.test directly.
# e.g. --cov-report html (or xml) for html/xml output or --junitxml junit.xml
# in order to write a coverage file that can be read by Jenkins.
addopts = --color=yes --cov=gammapy_plugin --cov-report=term -ra --ignore=gammapy_plugin/test --ignore=gammapy_plugin/_version.py
log_cli = 1
log_cli_level = INFO
testpaths = gammapy_plugin/test 
norecursedirs = gammapy_plugin/test

[tool:isort]
profile = black

[versioneer]
VCS=git
style=pep440
versionfile_source=gammapy_plugin/_version.py
versionfile_build=gammapy_plugin/_version.py
tag_prefix=v
parentdir_prefix=gammapy_plugin-

[flake8]
max-line-length = 88
extend-ignore = E203,E701


