cuts:
  th2cut: 0.008
  
data:
  anasum: /home/tobi/sw/gammapy-plugin/datafiles/
fileio:
  outdir: /data/tobi/gammapy-plugin_test/
selection:
  emax: 10
  emin: 0.1
  exc_on_region_radius: 0.3
  exc_radius: 0.3
  nbin: 6
  target: Crab
