name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "README.md"
      - "**/docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    branches:
      - master
      - dev
  schedule:
    - cron: "0 11 * * 1"

jobs:
  build:
    name: Build and Test (${{ matrix.os}}, Python ${{ matrix.python-version}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.12"
            quick: true
            gammapy_data: /home/runner/work/gammapy_data
          - os: ubuntu-latest
            python-version: "3.11"
            quick: false
            gammapy_data: /home/runner/work/gammapy_data

    if: ${{ github.event_name == 'push' }} || matrix.quick == true

    env:
      GAMMAPY_DATA: ${{ matrix.gammapy_data }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools flake8 ipython h5py coverage pytest pytest-cov cython codecov
          pip install --upgrade git+https://github.com/PreisTo/astromodels.git@dev
          pip install --upgrade git+https://github.com/PreisTo/threeML.git@dev
          pip install --upgrade git+https://github.com/gammapy/gammapy.git@main

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Test with pytest
        run: |
          git clone https://github.com/gammapy/gammapy-data.git $GAMMAPY_DATA
          pip install .
          python -m gammapy_plugin.data.create_test_datasets
          python -m pytest -vv --cov=gammapy_plugin/ --cov-report=xml
        env:
          NUMBA_DISABLE_JIT: 0

      - name: Upload coverage to Codecov
        if: matrix.quick == false
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install twine
        run: python -m pip install twine
      - name: Build package
        run: |
              pip install --upgrade setuptools
              python setup.py sdist
      - name: List result
        run: ls -l dist
      - name: Check long_description
        run: python -m twine check dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish package
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install twine
        run: python -m pip install twine
      - name: Build package
        run: |
              pip install --upgrade setuptools
              python setup.py sdist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
