name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11","3.12"] # these are requirements from astropy und gammapy

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools flake8 ipython h5py coverage pytest pytest-cov cython codecov
        # needed for bug_fix py3.12.x install
        pip install --upgrade git+https://github.com/threeml/astromodels.git 
        pip install --upgrade git+https://github.com/threeml/threeML.git
        pip install --upgrade gammapy --use-pep517
        python setup.py install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Test with pytest
      run: | 
        export GAMMAPY_DATA=$HOME/data
        mkdir -p $GAMMAPY_DATA
        git clone https://github.com/gammapy/gammapy-data.git $GAMMAPY_DATA
        python -m pytest -vv --cov=gammapy_plugin/ --cov-report=xml
      env:
        NUMBA_DISABLE_JIT: 0
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install twine
        run: python -m pip install twine
      - name: Build package
        run: python setup.py sdist
      - name: List result
        run: ls -l dist
      - name: Check long_description
        run: python -m twine check dist/*

        


  publish:
    needs: build
    runs-on: ubuntu-latest
    name: Publish package
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install twine
      run: python -m pip install twine
    - name: Build package
      run: python setup.py sdist
    - uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_UPLOAD_TOKEN }}

