name: Docs
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - dev
  release:

permissions:
  contents: write       # 'write' access to repository contents
  pull-requests: write  # 'write' access to pull requests

jobs:
  build-notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set SHA
        run: |
          SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          echo "SHA=$SHA" >> "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install black ultranest
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Execute the notebooks
        shell: bash -l {0}
        run: |
          export GAMMAPY_DATA="/home/runner/work/gammapy_data"
          mkdir -p $GAMMAPY_DATA
          git clone https://github.com/gammapy/gammapy-data.git $GAMMAPY_DATA
          jupytext --to ipynb --pipe black --execute docs/md_docs/*.md
          mkdir -p docs/notebooks
          mv docs/md_docs/*.ipynb docs/notebooks
          echo "Next - uploading artifacts for sha ${SHA}"

      - uses: actions/upload-artifact@v7
        with:
          name: notebooks-for-${{ env.SHA }}
          path: docs/notebooks

      - name: Trigger RTD 
        shell: bash -l {0}
        run: |
          curl -X POST \
            "https://app.readthedocs.org/api/v3/projects/gammapy-plugin/versions/${PR_NUMBER}/builds/" \
            -H "Authorization: Token $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"branch\": \"${BRANCH}\"
            }"

        env:
          TOKEN: ${{ secrets.RTD_API }}
          BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          PR_NUMBER: ${{ github.event.number || 'latest' }}
        
  pages:
    needs: build-notebooks
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - name: Set SHA
        run: |
          SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          echo "SHA=$SHA" >> "$GITHUB_ENV"

      - id: get_artifacts
        uses: actions/download-artifact@v8
        with:
          name: notebooks-for-${{ env.SHA }}
          path: docs/notebooks
      - id: deployment
        uses: sphinx-notes/pages@v3
