name: Docs
on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - dev
  release:

permissions:
  contents: write       # 'write' access to repository contents
  pull-requests: write  # 'write' access to pull requests

jobs:
  build-notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r docs/requirements.txt

      - name: Execute the notebooks
        shell: bash -l {0}
        run: |
          export GAMMAPY_DATA="/home/runner/work/gammapy_data"
          mkdir -p $GAMMAPY_DATA
          git clone https://github.com/gammapy/gammapy-data.git $GAMMAPY_DATA
          jupytext --to ipynb --pipe black --execute docs/md_docs/*.md
          mkdir -p docs/notebooks
          mv docs/md_docs/*.ipynb docs/notebooks
          echo "Next - uploading artifacts for sha ${{ github.sha }}"

      - uses: actions/upload-artifact@v6
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/notebooks
